---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: newunicorn
    spec:
      containers:
      - name: postgres
        image: postgres:9.4.5
        env:
          - name: POSTGRES_USER
            value: drkiq
          - name: POSTGRES_PASSWORD
            value: yourpassword        